org: mnamvar
app: ses-service
service: SES-with-UI
frameworkVersion: '3'

custom:
  tableName: 'users-table-${sls:stage}'
  region: ${self:provider.region}

provider:
  name: aws
  runtime: nodejs18.x
  region: ca-central-1
  profile: serverless-admin
  stage: dev

  iam:
    role:
      statements:
        - Effect: Allow
          Action: "SNS:Publish*"
          Resource: "*"

        - Effect: Allow
          Action: "ses:*"
          Resource: "*"

        - Effect: Allow
          Action: "s3:*"
          Resource: "*"

        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ UsersTable, Arn ]
  environment:
    USERS_TABLE: ${self:custom.tableName}
    REGION: ${self:provider.region} 
    SNS_TOPIC_ARN: 
      Fn::GetAtt:
        - QuotesSNSTopic
        - Arn

functions:
  create:
    handler: handler/handler.createContact
    events:
      - http:
          path: /contact-us
          method: post
          cors: true

  getQoutes:
    handler: handler/getQoutes.getQoutes
    events:
      - http:
          path: /qoutes
          method: get
          cors: true

  subscribe:
    handler: handler/subscribeUser.subscribeUser
    events:
      - http:
          path: /subscribe
          method: post
          cors: true

  staticMailer:
    handler: handler/staticMailer.staticMailer
    events:
      - http:
          path: /static-mailer
          method: post
          cors: true

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}

    QuotesSNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: quotes-message-${self:provider.stage}

    QuotesSNSSubscribe:
      Type: AWS::SNS::Subscription
      Properties: 
        DeliveryPolicy:
          healthyRetryPolicy:
            numRetries: 10
            minDelayTarget: 10
            maxDelayTarget: 60
        Endpoint: mnamvarcfd@gmail.com
        Protocol: email
        Region: ${self:provider.region}
        TopicArn: !Ref QuotesSNSTopic