org: mnamvar
app: ses-service
service: SES-with-UI
frameworkVersion: '3'

custom:
  tableName: 'users-table-${sls:stage}'
  region: ${self:provider.region}

provider:
  name: aws
  runtime: nodejs18.x
  region: ca-central-1
  profile: serverless-admin
  stage: dev

  iam:
    role:
      statements:
        - Effect: Allow
          Action: "ses:*"
          Resource: "*"
        - Effect: Allow
          Action: "s3:*"
          Resource: "*"
  #       - Effect: Allow
  #         Action:
  #           - dynamodb:Query
  #           - dynamodb:Scan
  #           - dynamodb:GetItem
  #           - dynamodb:PutItem
  #           - dynamodb:UpdateItem
  #           - dynamodb:DeleteItem
  #         Resource:
  #           - Fn::GetAtt: [ UsersTable, Arn ]
  environment:
    USERS_TABLE: ${self:custom.tableName}
    REGION: ${self:provider.region} 

functions:
  create:
    handler: handler/handler.createContact
    events:
      - http:
          path: /contact-us
          method: post
          cors: true

  getQoutes:
    handler: handler/getQoutes.getQoutes
    events:
      - http:
          path: /qoutes
          method: get
          cors: true

# resources:
#   Resources:
#     UsersTable:
#       Type: AWS::DynamoDB::Table
#       Properties:
#         AttributeDefinitions:
#           - AttributeName: userId
#             AttributeType: S
#         KeySchema:
#           - AttributeName: userId
#             KeyType: HASH
#         BillingMode: PAY_PER_REQUEST
#         TableName: ${self:custom.tableName}
